import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/section/hero.jsx'
import Navbar from '../components/ui/Navbar.jsx'
import Wrapper from '../components/ui/wrapper.jsx'


export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
 
        <Hero/>
       
      

  
      </div>


  )
}
